spring:
  profiles:
    include:
      - database
      - springdoc
      - jwt
      - redis
      - s3
      - mail
      - payment
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart: # MULTIPART (MultipartProperties) Enable support of multipart uploads.
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      encoding: UTF-8
      schema-locations: classpath:index.sql
  security:
    user:
      name: ${SECURITY_USER_NAME:user}
      password: ${SECURITY_USER_PASSWORD:1q2w3e4r}
  messages:
    encoding: UTF-8
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

server:
  port: ${SERVER_PORT:8089}

logging.level:
  org.hibernate.SQL: debug
  org.springframework.core.LocalVariableTableParameterNameDiscoverer: error

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics