# AWS S3
cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET_NAME}
      url: ${S3_URL}
#      arn:aws:s3:::shopimgstorage
    region:
      static: ap-northeast-2
    stack:
      auto: false