spring:
  datasource:
    master:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: ${MASTER_DB_URL:jdbc:mysql://localhost:3307/today-table}
        username: ${MASTER_DB_USERNAME:root}
        password: ${MASTER_DB_PASSWORD:rootpassword}
        maximum-pool-size: 10           # CPU 2개 기준
        minimum-idle: 2                 # 유휴 커넥션 수 절약
        idle-timeout: 300000            # 5분
        max-lifetime: 900000            # 15분
        connection-timeout: 3000        # 3초
        validation-timeout: 2000        # 2초

    slave:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: ${SLAVE_DB_URL:jdbc:mysql://localhost:3307/today-table}
        username: ${SLAVE_DB_USERNAME:root}
        password: ${SLAVE_DB_PASSWORD:rootpassword}
        maximum-pool-size: 10           # CPU 2개 기준
        minimum-idle: 2                 # 유휴 커넥션 수 절약
        idle-timeout: 300000            # 5분
        max-lifetime: 900000            # 15분
        connection-timeout: 3000        # 3초
        validation-timeout: 2000        # 2초
