package store.myproject.onlineshop.domain.faillog;

public enum JobType {
    RECIPE_VIEW_COUNT_INCREMENT,
    CUSTOMER_ORDER_AMOUNT_INCREMENT,
    CUSTOMER_ORDER_AMOUNT_DECREMENT,
    REVIEW_COUNT_INCREMENT,
    REVIEW_COUNT_DECREMENT,
    LIKE_COUNT_INCREMENT,
    LIKE_COUNT_DECREMENT;
}
